version: "3"

services:
  # fastapi app
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi-service
    ports:
      - "5000:5000"
    env_file:
      - development.env

    # Database layer
  database:
    image: postgres:12.4
    container_name: fastapi-db
    env_file:
      - development.env
    expose:
     - "5432"
    volumes:
      - restxlab-data:/var/lib/postgresql/data

volumes:
  restxlab-data: